import { createAction } from '@reduxjs/toolkit';
import { Publications } from '../../models/publications';
import { ActionType } from '../constant-lib';

export type LoadRawAction = ReturnType<typeof loadRaw>;

export const loadRaw = createAction(ActionType.LoadRaw, () => ({
  payload: [
    {
      id: 'av22cj',
      name: 'Andre Viebke',
      year: 2019,
      pubs: 2,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'sumeaa',
      name: 'Suejb Memeti',
      year: 2019,
      pubs: 3,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'saplaa',
      name: 'Sabri Pllana',
      year: 2019,
      pubs: 9,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'gibraa',
      name: 'Giangiacomo Bravo',
      year: 2019,
      pubs: 12,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'dipeab',
      name: 'Diego Perez-Palacin',
      year: 2019,
      pubs: 3,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'anchaa',
      name: 'Angelos Chatzimparmpas',
      year: 2019,
      pubs: 3,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'frahaa',
      name: 'Fredrik Ahlgren',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'ramaaa',
      name: 'Rafael Messias Martins',
      year: 2019,
      pubs: 3,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'akemsi',
      name: 'Andreas Kerren',
      year: 2019,
      pubs: 8,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'vasiaa',
      name: 'Vasiliki Simaki',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'frpaab',
      name: 'Francis Palma',
      year: 2019,
      pubs: 2,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'jeluab',
      name: 'Jenny Lundberg',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'shhuab',
      name: 'Shiyan Hu',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'itmaaa',
      name: 'Italo Masiello',
      year: 2019,
      pubs: 3,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'frflaa',
      name: 'Francesco Flammini',
      year: 2019,
      pubs: 3,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'akumsi',
      name: 'Arianit Kurti',
      year: 2019,
      pubs: 7,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'ijumsi',
      name: 'Ilir Jusufi',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'wlomsi',
      name: 'Welf Löwe',
      year: 2019,
      pubs: 8,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'fidaaa',
      name: 'Fisnik Dalipi',
      year: 2019,
      pubs: 4,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'jlnmsi',
      name: 'Jonas Lundberg',
      year: 2019,
      pubs: 2,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'ya222ci',
      name: 'Yasser Alsouda',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'mifaab',
      name: 'Mike Farjam',
      year: 2019,
      pubs: 10,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'maskaa',
      name: 'Maria Skeppstedt',
      year: 2019,
      pubs: 3,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'kokuaa',
      name: 'Kostiantyn Kucher',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'dakoaa',
      name: 'Dan Kohen-Vacs',
      year: 2019,
      pubs: 2,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'mmimsi',
      name: 'Marcelo Milrad',
      year: 2019,
      pubs: 7,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'nuotaa',
      name: 'Nuno Otero',
      year: 2019,
      pubs: 2,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'majaac',
      name: 'Marc Jansen',
      year: 2019,
      pubs: 3,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'sehoaa',
      name: 'Sebastian Hönel',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'moeraa',
      name: 'Morgan Ericsson',
      year: 2019,
      pubs: 6,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'awimsi',
      name: 'Anna Wingkvist',
      year: 2019,
      pubs: 6,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'daweaa',
      name: 'Danny Weyns',
      year: 2019,
      pubs: 12,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'zekaaa',
      name: 'Zenun Kastrati',
      year: 2019,
      pubs: 8,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'shyoaa',
      name: 'Shahrouz Yousefi',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'maulab',
      name: 'Maria Ulan',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'johaac',
      name: 'Johan Hagelbäck',
      year: 2019,
      pubs: 6,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'alsoaa',
      name: 'Alisa Lincke',
      year: 2019,
      pubs: 6,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'tohto',
      name: 'Tobias Olsson',
      year: 2019,
      pubs: 2,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'dl222mm',
      name: 'David Lozano Prieto',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'roheaa',
      name: 'Romain Christian Herault',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'mhteaa',
      name: 'Mhretab Kidane Tewele',
      year: 2019,
      pubs: 2,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'stshaa',
      name: 'Stepan Shevtsov',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'mp222tb',
      name: 'Mauro Pappaterra',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'aralaa',
      name: 'Aris Alissandrakis',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'nireaa',
      name: 'Nico Reski',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'mhsaaa',
      name: 'Mehdi Saman Azari',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'macaab',
      name: 'Mauro Caporuscio',
      year: 2019,
      pubs: 2,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'nakhaa',
      name: 'Narges Khakpour',
      year: 2019,
      pubs: 2,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'chskab',
      name: 'Charilaos Skandylas',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'sb223ce',
      name: 'Sarpreet Singh Buttar',
      year: 2019,
      pubs: 2,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'midaab',
      name: "Mirko D'Angelo",
      year: 2019,
      pubs: 2,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'jozaaa',
      name: 'Jorge Luis Zapico',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'janmsi',
      name: 'Jesper Andersson',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'author0',
      name: 'M. Usman Iftikhar',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'jtomsi',
      name: 'Joachim Toft',
      year: 2019,
      pubs: 8,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'yuchaa',
      name: 'Yuanyuan Chen',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'pawaaa',
      name: 'Patrik Wahlberg',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'hpamsi',
      name: 'Hanna Palmér',
      year: 2019,
      pubs: 3,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'hfnmsi',
      name: 'Helena Roos',
      year: 2019,
      pubs: 4,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'akhmsi',
      name: 'Andrei Khrennikov',
      year: 2019,
      pubs: 17,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'jstmsi',
      name: 'Jeppe Skott',
      year: 2019,
      pubs: 2,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'tlito',
      name: 'Torsten Lindström',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'angrac',
      name: 'Helena Grundén',
      year: 2019,
      pubs: 2,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'poeh222',
      name: 'Ehsan Pourhadi',
      year: 2019,
      pubs: 4,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'bnimsi',
      name: 'Börje Nilsson',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'jofrab',
      name: 'Jonas Nordqvist',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'rpemsi',
      name: 'Roger Pettersson',
      year: 2019,
      pubs: 2,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'naagab',
      name: 'Nacira Agram',
      year: 2019,
      pubs: 7,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'eyumsi',
      name: 'Ekaterina Yurova',
      year: 2019,
      pubs: 2,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'author1',
      name: 'Giuseppe Iurato',
      year: 2019,
      pubs: 2,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'eolco',
      name: 'Constanta Olteanu',
      year: 2019,
      pubs: 3,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'luolaa',
      name: 'Lucian Olteanu',
      year: 2019,
      pubs: 2,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'aebmsi',
      name: 'Andreas Ebbelind',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'hestab',
      name: 'Helén Sterner',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'bwehum',
      name: 'Bärbel Westphal',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'ambhum',
      name: 'Angela Marx Åberg',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'jutyaa',
      name: 'Jukka Tyrkkö',
      year: 2019,
      pubs: 8,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'nihaaa',
      name: 'Nicklas Hållén',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'nisaaa',
      name: 'Niklas Salmose',
      year: 2019,
      pubs: 6,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'milaab',
      name: 'Mikko Laitinen',
      year: 2019,
      pubs: 3,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'mlvhum',
      name: 'Magnus Levin',
      year: 2019,
      pubs: 7,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'allaaa',
      name: 'Alexander Lakaw',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'makaam',
      name: 'Marie Källkvist',
      year: 2019,
      pubs: 7,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'psihum',
      name: 'Per Sivefors',
      year: 2019,
      pubs: 3,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'frheaa',
      name: 'Fredrik Heinat',
      year: 2019,
      pubs: 5,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'anpaac',
      name: 'Anne Holm',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'heavaa',
      name: 'Helen Avery',
      year: 2019,
      pubs: 4,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'mifraa',
      name: 'Mike Classon Frangos',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'liluaa',
      name: 'Liviu Lutas',
      year: 2019,
      pubs: 2,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'spmeaa',
      name: 'Špela Mežek',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'clohum',
      name: 'Corina Löwe',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'jestaa',
      name: 'Jenny Ström Herold',
      year: 2019,
      pubs: 2,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'khojo',
      name: 'Johan Höglund',
      year: 2019,
      pubs: 3,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'aksiaa',
      name: 'Aki Siegel',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'crohum',
      name: 'Christina Rosén',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'frolab',
      name: 'Fredrik Olsson',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'reduaa',
      name: 'Rebecca Duncan',
      year: 2019,
      pubs: 3,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'khuhum',
      name: 'Kirsten Husung',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'athhum',
      name: 'Anna Thyberg',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'oerhum',
      name: 'Olof Eriksson',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'legoaa',
      name: 'Leticia Gòmez',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'estje',
      name: 'Jean Stevenson-Ågren',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'falch',
      name: 'Christopher Allen',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'krida',
      name: 'David Richardson',
      year: 2019,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'vasiaa',
      name: 'Vasiliki Simaki',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'maskaa',
      name: 'Maria Skeppstedt',
      year: 2020,
      pubs: 2,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'kokuaa',
      name: 'Kostiantyn Kucher',
      year: 2020,
      pubs: 4,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'akemsi',
      name: 'Andreas Kerren',
      year: 2020,
      pubs: 9,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'nabmsi',
      name: 'Nadeem Abbas',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'janmsi',
      name: 'Jesper Andersson',
      year: 2020,
      pubs: 2,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'daweaa',
      name: 'Danny Weyns',
      year: 2020,
      pubs: 5,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'gibraa',
      name: 'Giangiacomo Bravo',
      year: 2020,
      pubs: 7,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'nireaa',
      name: 'Nico Reski',
      year: 2020,
      pubs: 3,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'aralaa',
      name: 'Aris Alissandrakis',
      year: 2020,
      pubs: 3,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'frflaa',
      name: 'Francesco Flammini',
      year: 2020,
      pubs: 5,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'macaab',
      name: 'Mauro Caporuscio',
      year: 2020,
      pubs: 6,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'nakhaa',
      name: 'Narges Khakpour',
      year: 2020,
      pubs: 3,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'ps222vt',
      name: 'Prasannjeet Singh',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'saplaa',
      name: 'Sabri Pllana',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'mhsaaa',
      name: 'Mehdi Saman Azari',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'anchaa',
      name: 'Angelos Chatzimparmpas',
      year: 2020,
      pubs: 3,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'ramaaa',
      name: 'Rafael Messias Martins',
      year: 2020,
      pubs: 7,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'ijumsi',
      name: 'Ilir Jusufi',
      year: 2020,
      pubs: 2,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'zekaaa',
      name: 'Zenun Kastrati',
      year: 2020,
      pubs: 5,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'akumsi',
      name: 'Arianit Kurti',
      year: 2020,
      pubs: 2,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'mifaab',
      name: 'Mike Farjam',
      year: 2020,
      pubs: 3,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'midaab',
      name: "Mirko D'Angelo",
      year: 2020,
      pubs: 6,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'alsoaa',
      name: 'Alisa Lincke',
      year: 2020,
      pubs: 3,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'johaac',
      name: 'Johan Hagelbäck',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'jlnmsi',
      name: 'Jonas Lundberg',
      year: 2020,
      pubs: 3,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'maulab',
      name: 'Maria Ulan',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'wlomsi',
      name: 'Welf Löwe',
      year: 2020,
      pubs: 3,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'moeraa',
      name: 'Morgan Ericsson',
      year: 2020,
      pubs: 3,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'awimsi',
      name: 'Anna Wingkvist',
      year: 2020,
      pubs: 3,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'sehoaa',
      name: 'Sebastian Hönel',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'fidaaa',
      name: 'Fisnik Dalipi',
      year: 2020,
      pubs: 2,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'jozaaa',
      name: 'Jorge Luis Zapico',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'author2',
      name: 'Masoud Fatemi',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'chskab',
      name: 'Charilaos Skandylas',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'madaac',
      name: 'Mattias Davidsson',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'mmimsi',
      name: 'Marcelo Milrad',
      year: 2020,
      pubs: 5,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'faedaa',
      name: 'Farid Edrisi',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'dipeab',
      name: 'Diego Perez-Palacin',
      year: 2020,
      pubs: 2,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'frahaa',
      name: 'Fredrik Ahlgren',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'ttoda',
      name: 'Daniel Toll',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'rs222tg',
      name: 'Rasmus Svensson',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'at222ux',
      name: 'Adell Tatrous',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'frpaab',
      name: 'Francis Palma',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'heghaa',
      name: 'Hemant Ghayvat',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'zemoaa',
      name: 'Zeynab Mohseni',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'itmaaa',
      name: 'Italo Masiello',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'rd222dv',
      name: 'Ruth Dirnfeld',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'dakoaa',
      name: 'Dan Kohen-Vacs',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'kych222',
      name: 'Chronis Kynigos',
      year: 2020,
      pubs: 2,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'samoaa',
      name: 'Sarwar J. Morshed',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'juraaa',
      name: 'Juwel Rana',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'nuotaa',
      name: 'Nuno Otero',
      year: 2020,
      pubs: 2,
      department: 'Dept. of Computer Science and Media Technology (DM)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'akhmsi',
      name: 'Andrei Khrennikov',
      year: 2020,
      pubs: 19,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'pawaaa',
      name: 'Patrik Wahlberg',
      year: 2020,
      pubs: 3,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'naagab',
      name: 'Nacira Agram',
      year: 2020,
      pubs: 2,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'ahimsi',
      name: 'Astrid Hilbert',
      year: 2020,
      pubs: 6,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'poeh222',
      name: 'Ehsan Pourhadi',
      year: 2020,
      pubs: 4,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'jtomsi',
      name: 'Joachim Toft',
      year: 2020,
      pubs: 9,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'rpemsi',
      name: 'Roger Pettersson',
      year: 2020,
      pubs: 7,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'chenab',
      name: 'Christian Engström',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'hpamsi',
      name: 'Hanna Palmér',
      year: 2020,
      pubs: 5,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'eolco',
      name: 'Constanta Olteanu',
      year: 2020,
      pubs: 2,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'jofrab',
      name: 'Jonas Nordqvist',
      year: 2020,
      pubs: 3,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'tlito',
      name: 'Torsten Lindström',
      year: 2020,
      pubs: 2,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'elnaaa',
      name: 'Elmira Nabizadeh Morsalfard',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'bjliaa',
      name: 'Björn Lindenberg',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'klimsi',
      name: 'Karl-Olof Lindahl',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'frpeab',
      name: 'Fritiof Wallentin',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'hfnmsi',
      name: 'Helena Roos',
      year: 2020,
      pubs: 2,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'author1',
      name: 'Giuseppe Iurato',
      year: 2020,
      pubs: 4,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'angrac',
      name: 'Helena Grundén',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'mpzmsi',
      name: 'Miguel Perez',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'jstmsi',
      name: 'Jeppe Skott',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Mathematics (MA)',
      faculty: 'Faculty of Technology (FTK)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'makaam',
      name: 'Marie Källkvist',
      year: 2020,
      pubs: 5,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'crohum',
      name: 'Christina Rosén',
      year: 2020,
      pubs: 3,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'chohum',
      name: 'Charlotte Hommerberg',
      year: 2020,
      pubs: 2,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'nisaaa',
      name: 'Niklas Salmose',
      year: 2020,
      pubs: 3,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'reduaa',
      name: 'Rebecca Duncan',
      year: 2020,
      pubs: 2,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'psihum',
      name: 'Per Sivefors',
      year: 2020,
      pubs: 4,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'khojo',
      name: 'Johan Höglund',
      year: 2020,
      pubs: 5,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'ambhum',
      name: 'Angela Marx Åberg',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'estje',
      name: 'Jean Stevenson-Ågren',
      year: 2020,
      pubs: 3,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'jutyaa',
      name: 'Jukka Tyrkkö',
      year: 2020,
      pubs: 6,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'milaab',
      name: 'Mikko Laitinen',
      year: 2020,
      pubs: 4,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'heavaa',
      name: 'Helen Avery',
      year: 2020,
      pubs: 3,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'mifraa',
      name: 'Mike Classon Frangos',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'oerhum',
      name: 'Olof Eriksson',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'frheaa',
      name: 'Fredrik Heinat',
      year: 2020,
      pubs: 2,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'clohum',
      name: 'Corina Löwe',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'roenaa',
      name: 'Robin Engström',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'liluaa',
      name: 'Liviu Lutas',
      year: 2020,
      pubs: 2,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'khuhum',
      name: 'Kirsten Husung',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'bwehum',
      name: 'Bärbel Westphal',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
    {
      id: 'anpaac',
      name: 'Anne Holm',
      year: 2020,
      pubs: 1,
      department: 'Dept. of Languages (SPR)',
      faculty: 'Faculty of Arts and Humanities (FKH)',
      university: 'Linnaeus University (LNU)',
    },
  ] as Publications[],
}));
